language: r
warnings_are_errors: true
sudo: true

r:
  - oldrel
  - release
  - devel

r_binary_packages:
  - rgdal
  - sp
  - rgeos

notifications:
  email:
    on_success: change
    on_failure: change